"""Shared helpers to emit HSK lesson data JS."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def hanzi_count(text: str) -> int:
    return len(re.findall(r"[\u4e00-\u9fff]", text))


def build_matchers(vocab: list[dict]) -> list[tuple[str, str]]:
    matchers: list[tuple[str, str]] = []
    for w in vocab:
        forms = w.get("match") or [w["hanzi"]]
        for form in forms:
            matchers.append((form, w["id"]))
    matchers.sort(key=lambda x: len(x[0]), reverse=True)
    return matchers


def tokenize(
    text: str,
    matchers: list[tuple[str, str]],
    blocked_if_inside: dict[str, tuple[str, ...]] | None = None,
) -> list[dict]:
    blocked_if_inside = blocked_if_inside or {}
    tokens: list[dict] = []
    i = 0
    n = len(text)
    plain: list[str] = []

    def flush() -> None:
        nonlocal plain
        if plain:
            tokens.append({"t": "".join(plain)})
            plain = []

    while i < n:
        matched = False
        for form, vid in matchers:
            if text.startswith(form, i):
                blocked = blocked_if_inside.get(vid, ())
                if any(text.startswith(b, i) for b in blocked if b != form):
                    continue
                flush()
                tokens.append({"t": form, "new": vid})
                i += len(form)
                matched = True
                break
        if not matched:
            plain.append(text[i])
            i += 1
    flush()
    return tokens


def emit_lesson(
    *,
    lesson: int,
    title: str,
    title_py: str,
    title_en: str,
    vocab: list[dict],
    paras: list[tuple[str, str, str]],
    blocked_if_inside: dict[str, tuple[str, ...]] | None = None,
    ignore_missing: set[str] | None = None,
) -> dict:
    matchers = build_matchers(vocab)
    paragraphs = []
    used: set[str] = set()
    total = 0
    for zh, py, en in paras:
        toks = tokenize(zh, matchers, blocked_if_inside)
        for t in toks:
            if t.get("new"):
                used.add(t["new"])
        total += hanzi_count(zh)
        paragraphs.append({"tokens": toks, "py": py, "en": en, "zh": zh})

    ignore_missing = ignore_missing or set()
    missing = [w["id"] for w in vocab if w["id"] not in used and w["id"] not in ignore_missing]
    payload = {
        "lesson": lesson,
        "title": title,
        "title_py": title_py,
        "title_en": title_en,
        "level": f"HSK 1 → Lesson {lesson}",
        "hanzi_count": total,
        "vocab": [{k: v for k, v in w.items() if k != "match"} for w in vocab],
        "script": paragraphs,
    }
    out = ROOT / "public" / "js" / f"hsk-lesson-{lesson}-data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    body = (
        f"/* Generated by scripts/_gen_hsk_lesson_{lesson}.py — do not edit by hand. */\n"
        f"window.HSK_LESSON_{lesson} = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + f";\nwindow.HSK_LESSON = window.HSK_LESSON_{lesson};\n"
    )
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out}")
    print(f"hanzi_count={total}")
    print(f"paragraphs={len(paragraphs)}")
    print(f"vocab={len(vocab)} used={len(used)}")
    if missing:
        print("MISSING highlights:", missing)
    return payload
